[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/cv4faces/OpenCV-Course/OpenCV-Basics/Binder-Numpy
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=22846b54644e33a02d50f9249640ce086b00bcf0760f5567
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=22846b54644e33a02d50f9249640ce086b00bcf0760f5567
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: 9dd528b0-d742-49a0-8e88-a74e9593c83d
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 9dd528b0-d742-49a0-8e88-a74e9593c83d
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 9dd528b0-d742-49a0-8e88-a74e9593c83d
[NotebookApp | INFO] Saving file at /Numpy Arrays Example.ipynb
[NotebookApp | WARNING] 404 GET /api/contents/Untitled.ipynb?content=0&_=1547101395387 (127.0.0.1): No such file or directory: Untitled.ipynb
[NotebookApp | WARNING] No such file or directory: Untitled.ipynb
[NotebookApp | WARNING] 404 GET /api/contents/Untitled.ipynb?content=0&_=1547101395387 (127.0.0.1) 1.74ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[NotebookApp | INFO] Uploading file to /Untitled.ipynb
[NotebookApp | INFO] Saving file at /Numpy Arrays Example.ipynb
[NotebookApp | WARNING] delete /Untitled.ipynb
[NotebookApp | INFO] Kernel shutdown: 9dd528b0-d742-49a0-8e88-a74e9593c83d
[NotebookApp | INFO] Creating new file in 
[NotebookApp | INFO] Saving file at /requirements.txt
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/cv4faces/OpenCV-Course/OpenCV-Basics/Binder-Numpy
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=f75f580ca87ff461c749fee1e48b3eb0a3d162726bfcd053
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f75f580ca87ff461c749fee1e48b3eb0a3d162726bfcd053
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Creating new file in 
[NotebookApp | INFO] Saving file at /environment.yml
[NotebookApp | INFO] Saving file at /environment.yml
[NotebookApp | WARNING] delete /requirements.txt
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/cv4faces/OpenCV-Course/OpenCV-Basics/Binder-Numpy
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=5cdc175730c1f9367e58dbf2eb1d3186feaac75f136c46d1
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=5cdc175730c1f9367e58dbf2eb1d3186feaac75f136c46d1
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: 9ef1b26b-1841-4f71-8436-067eab8f348f
[NotebookApp | INFO] Kernel shutdown: 9ef1b26b-1841-4f71-8436-067eab8f348f
[NotebookApp | INFO] Kernel started: 935c9d40-5676-4167-bfdb-a038cfd4c929
[NotebookApp | WARNING] Timeout waiting for kernel_info reply from 9ef1b26b-1841-4f71-8436-067eab8f348f
[NotebookApp | ERROR] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 9ef1b26b-1841-4f71-8436-067eab8f348f)
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 935c9d40-5676-4167-bfdb-a038cfd4c929
[NotebookApp | INFO] Saving file at /Cpp-Test.ipynb
[NotebookApp | INFO] Saving file at /Cpp-Test.ipynb
[NotebookApp | INFO] Starting buffering for 935c9d40-5676-4167-bfdb-a038cfd4c929:db5ca1081065428fa94f27776e882236
[NotebookApp | INFO] Kernel shutdown: 935c9d40-5676-4167-bfdb-a038cfd4c929
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 0 kernels
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/cv4faces/OpenCV-Course/OpenCV-Basics/Binder-Numpy
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=28c7b925883a4185569d40e32b66ecd4d7d13bfa309721a2
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=28c7b925883a4185569d40e32b66ecd4d7d13bfa309721a2
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Creating new file in 
[NotebookApp | INFO] Kernel started: 1dca55f0-98b4-40cc-aedf-a3e2d31b87c7
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 1dca55f0-98b4-40cc-aedf-a3e2d31b87c7
[NotebookApp | INFO] Starting buffering for 1dca55f0-98b4-40cc-aedf-a3e2d31b87c7:90eae57762bc4bfa9758b6a1d40287ea
[NotebookApp | INFO] Saving file at /includeLibraries.h
[NotebookApp | INFO] Saving file at /includeLibraries.h
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 1 kernel
[NotebookApp | INFO] Kernel shutdown: 1dca55f0-98b4-40cc-aedf-a3e2d31b87c7
[NotebookApp | ERROR] Exception while loading config file /etc/jupyter/nbgrader_config.py
    Traceback (most recent call last):
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 562, in _load_config_files
        config = loader.load_config()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 457, in load_config
        self._read_file_as_dict()
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/traitlets/config/loader.py", line 489, in _read_file_as_dict
        py3compat.execfile(conf_filename, namespace)
      File "/home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/ipython_genutils/py3compat.py", line 198, in execfile
        exec(compiler(f.read(), fname, 'exec'), glob, loc)
      File "/etc/jupyter/nbgrader_config.py", line 29
        "C++14": "// your code here\nthrow new Error();"
               ^
    SyntaxError: invalid syntax
[NotebookApp | INFO] Loading the validate_assignment nbgrader serverextension
[NotebookApp | INFO] nteract extension loaded from /home/hp/workfolder/python/anaconda3/lib/python3.6/site-packages/nteract_on_jupyter
[NotebookApp | INFO] Serving notebooks from local directory: /home/hp/workfolder/cv4faces/OpenCV-Course/OpenCV-Basics/Binder-Numpy
[NotebookApp | INFO] The Jupyter Notebook is running at:
[NotebookApp | INFO] http://localhost:8888/?token=aaf15a0c17f8049f25211a2dde1b9a7ef128f415505c5fb2
[NotebookApp | INFO] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[NotebookApp | CRITICAL] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=aaf15a0c17f8049f25211a2dde1b9a7ef128f415505c5fb2
[NotebookApp | INFO] Accepting one-time-token-authenticated connection from 127.0.0.1
[NotebookApp | INFO] Kernel started: b384b1a0-c443-4342-9d9d-330d10ade065
[NotebookApp | WARNING] 404 GET /notebooks/includeLibraries.png (127.0.0.1): No such file or directory: includeLibraries.png
[NotebookApp | WARNING] 404 GET /notebooks/includeLibraries.png (127.0.0.1) 79.52ms referer=http://localhost:8888/notebooks/Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] 302 GET /notebooks/girl.jpg (127.0.0.1) 1.54ms
[NotebookApp | WARNING] 404 GET /notebooks/result_Landmarks.jpg (127.0.0.1): No such file or directory: result_Landmarks.jpg
[NotebookApp | WARNING] 404 GET /notebooks/result_Landmarks.jpg (127.0.0.1) 4.05ms referer=http://localhost:8888/notebooks/Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Kernel started: 502994a3-611f-4cb6-bcda-709ffbb879cd
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel b384b1a0-c443-4342-9d9d-330d10ade065
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 502994a3-611f-4cb6-bcda-709ffbb879cd
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Starting buffering for 502994a3-611f-4cb6-bcda-709ffbb879cd:5a46c0fc322546ad8407e5401cadad62
[NotebookApp | INFO] Kernel restarted: 502994a3-611f-4cb6-bcda-709ffbb879cd
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel 502994a3-611f-4cb6-bcda-709ffbb879cd
[NotebookApp | INFO] Restoring connection for 502994a3-611f-4cb6-bcda-709ffbb879cd:5a46c0fc322546ad8407e5401cadad62
[NotebookApp | INFO] Replaying 6 buffered messages
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection.ipynb
[NotebookApp | INFO] Starting buffering for 502994a3-611f-4cb6-bcda-709ffbb879cd:5a46c0fc322546ad8407e5401cadad62
[NotebookApp | INFO] Creating new notebook in 
[NotebookApp | INFO] Kernel started: b05495a9-8a91-40b6-83b6-e0dbeb2d78fc
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel b05495a9-8a91-40b6-83b6-e0dbeb2d78fc
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection_cpp.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection_Python.ipynb
[NotebookApp | INFO] Kernel started: ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6
[NotebookApp | INFO] Starting buffering for ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6:521a61c0c9204f27848b3cfd0282bfc0
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection_Python.ipynb
[NotebookApp | WARNING] delete /facialLandmarkDetector.py
[NotebookApp | INFO] Adapting to protocol v5.1 for kernel ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6
[NotebookApp | INFO] Starting buffering for ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6:44afc55e56704f719b28a2ccfd23e11a
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection_Python.ipynb
[NotebookApp | INFO] Saving file at /Facial_Landmark_Detection_Python.ipynb
[NotebookApp | INFO] Saving file at /Cpp-Test.ipynb
[NotebookApp | INFO] Starting buffering for b384b1a0-c443-4342-9d9d-330d10ade065:93e003199f9849e8ace544a3df1ff968
[NotebookApp | INFO] Starting buffering for b05495a9-8a91-40b6-83b6-e0dbeb2d78fc:e08eb8477b2b412fb513299c916a08b9
[NotebookApp | INFO] interrupted
[NotebookApp | CRITICAL] Shutdown confirmed
[NotebookApp | INFO] Shutting down 4 kernels
[NotebookApp | INFO] Kernel shutdown: b384b1a0-c443-4342-9d9d-330d10ade065
[NotebookApp | INFO] Kernel shutdown: 502994a3-611f-4cb6-bcda-709ffbb879cd
[NotebookApp | INFO] Kernel shutdown: b05495a9-8a91-40b6-83b6-e0dbeb2d78fc
[NotebookApp | INFO] Kernel shutdown: ea0a2266-e0ba-4d22-8a88-b6b678ea2bf6
